# Generated by Django 4.2.7 on 2023-11-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('change_message', models.TextField()),
                ('action_flag', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpDetails',
            fields=[
                ('pgm_id', models.AutoField(db_column='PGM_ID', primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, max_length=40000, null=True)),
                ('address', models.CharField(blank=True, max_length=40000, null=True)),
                ('dob', models.IntegerField(blank=True, db_column='Dob', null=True)),
                ('phone_number', models.IntegerField(blank=True, db_column='Phone_Number', null=True)),
                ('email_id', models.CharField(blank=True, db_column='Email_Id', max_length=40000, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=40000, null=True)),
                ('center', models.IntegerField(blank=True, db_column='Center', null=True)),
                ('designation', models.CharField(blank=True, db_column='Designation', max_length=40000, null=True)),
                ('date_of_joining', models.IntegerField(blank=True, db_column='Date_of_Joining', null=True)),
                ('education_qualification', models.CharField(blank=True, db_column='Education_Qualification', max_length=40000, null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('resource_type', models.IntegerField(blank=True, db_column='Resource_Type', null=True)),
                ('date_of_resigning', models.IntegerField(blank=True, db_column='Date_of_resigning', null=True)),
                ('bank_name', models.CharField(blank=True, db_column='Bank_Name', max_length=40000, null=True)),
                ('name_as_per_bank', models.CharField(blank=True, db_column='Name_As_per_Bank', max_length=40000, null=True)),
                ('account_number', models.IntegerField(blank=True, db_column='Account_Number', null=True)),
                ('ifsc', models.CharField(blank=True, db_column='IFSC', max_length=40000, null=True)),
                ('branch', models.CharField(blank=True, db_column='Branch', max_length=40000, null=True)),
                ('account_type', models.IntegerField(blank=True, db_column='Account_Type', null=True)),
            ],
            options={
                'db_table': 'Emp_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('pgm_id', models.AutoField(db_column='PGM_ID', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('program', models.IntegerField(blank=True, null=True)),
                ('project', models.CharField(blank=True, db_column='Project', max_length=40000, null=True)),
                ('activity', models.CharField(blank=True, db_column='Activity', max_length=40000, null=True)),
                ('center_type', models.IntegerField(blank=True, db_column='Center_Type', null=True)),
                ('trainer_type', models.IntegerField(blank=True, db_column='Trainer_Type', null=True)),
                ('sponsor', models.IntegerField(blank=True, db_column='Sponsor', null=True)),
                ('beneficiaries', models.IntegerField(blank=True, db_column='Beneficiaries', null=True)),
                ('category', models.IntegerField(blank=True, db_column='Category', null=True)),
                ('duration', models.IntegerField(blank=True, db_column='Duration', null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('comments', models.CharField(blank=True, db_column='Comments', max_length=40000, null=True)),
            ],
            options={
                'db_table': 'Program',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramDetails',
            fields=[
                ('pgm_id', models.AutoField(db_column='PGM_ID', primary_key=True, serialize=False)),
                ('program', models.IntegerField(blank=True, db_column='Program', null=True)),
                ('project', models.CharField(blank=True, db_column='Project', max_length=40000, null=True)),
                ('no_of_dropouts', models.IntegerField(blank=True, db_column='No_of_dropouts', null=True)),
                ('attendance_percentage', models.IntegerField(blank=True, db_column='Attendance_percentage', null=True)),
                ('pre_assessment_score', models.IntegerField(blank=True, db_column='Pre_Assessment_Score', null=True)),
                ('mid_assessment_score', models.IntegerField(blank=True, db_column='Mid_Assessment_Score', null=True)),
                ('post_assessment_score', models.IntegerField(blank=True, db_column='Post_Assessment_Score', null=True)),
                ('closure_report', models.CharField(blank=True, db_column='Closure_report', max_length=40000, null=True)),
            ],
            options={
                'db_table': 'Program_details',
                'managed': False,
            },
        ),
    ]
